### ISSUE TITLE
iOS remote compile failed

### ISSUE THREAD

**Issue by jashking** [Noesis/UE4Plugin#12]
> NoesisInstance.cpp(32,1):  error: unknown type name 'FStatGroup_STATGROUP_Noesis'
DECLARE_CYCLE_STAT(TEXT("NoesisInstance::Update"), STAT_NoesisInstance_Update, STATGROUP_Noesis);
^

Is it better to use [IWYU](https://docs.unrealengine.com/en-us/Programming/UnrealBuildSystem/IWYUReferenceGuide)?

**Comment by hcpizzi** [comment]
That's because IOS doesn't use precompiled headers. I have it fixed locally. Give me a few minutes to push the change.

**Comment by hcpizzi** [comment]
It should be fixed by commit [https://github.com/Noesis/UE4Plugin/commit/dff8e6dabddd768b6044c76f9f388a792dd08761](dff8e6dabddd768b6044c76f9f388a792dd08761)

**Comment by jashking** [comment]
Yes, it works now.
