### ISSUE TITLE
what' the right way to add plugin with versions of Unreal Engine built from the source code in GitHub

### ISSUE THREAD

**Issue by idnemo** [Noesis/UE4Plugin#16]
When I run InstallPlugin.bat, it always gave me below log, seems the script can't find the engine. 
Found the following engine installations:
Plugin is not installed in any of the installed engines. Looking for projects...
Couldn't find an engine for the plugin. Exiting...

**Comment by hcpizzi** [comment]
It should auto-detect them. Could you answer me a few questions about your setup?
- What platform are you using? Win, Mac?
- Are you using a version of Unreal Engine installed from the Epic Games Launcher, or built from the source code in GitHub?
- Are you installing the plugin as an Engine or Project plugin?

Thank you.
