### ISSUE TITLE
scoreboard could not be compiled try rebuilding from source manually

### ISSUE THREAD

**Issue by yingnierxiao** [Noesis/UE4Plugin#18]
scoreboard could not be compiled try rebuilding from source manually
mac   and ue4 4.22.3version

**Comment by hcpizzi** [comment]
Hi yingnierxiao,

I just tested it and it worked for me. Can you tell me what steps you followed and what's the error you're getting?

Thank you

**Comment by yingnierxiao** [comment]
<img width="422" alt="1" src="https://user-images.githubusercontent.com/3435706/62361813-5767ae80-b54e-11e9-9129-66e8757722d7.png">
<img width="797" alt="2" src="https://user-images.githubusercontent.com/3435706/62361815-59317200-b54e-11e9-88d2-f019b3427756.png">
<img width="415" alt="3" src="https://user-images.githubusercontent.com/3435706/62361817-5a629f00-b54e-11e9-904a-7cd3ec7f1211.png">
