### ISSUE TITLE
Cant Get Working With ShooterGame

### ISSUE THREAD

**Issue by kingkylec** [Noesis/UE4Plugin#19]
I have it working but the main menu dosen't work with the plugin.. The other parts do just not the main menu any help would be great!

**Comment by hcpizzi** [comment]
Hi kingkylec,

I just tested it, using UE 4.22.3 and the latest version 2.2.4 of the plugin, which you can [download from here](https://www.noesisengine.com/developers/downloads.php), and it works.

What's the problem you're having?

**Comment by kingkylec** [comment]
Right now the problem is when packaging for windows 64, the main menu never
shows up.

**Comment by kingkylec** [comment]
Okay well fixed the main menu not coming up in a packaged game, now the in
game menu is not working when in the game. I press escape, it shows mouse
cursor but no menu.

**Comment by hcpizzi** [comment]
Hi,

I just tested again and it still works for me. Have you checked the logs, in case something shows up there?

**Comment by jesusdesantos** [comment]
Could you please attach a video showing all the steps since the beginning?
