### ISSUE TITLE
UE 4.25 support

### ISSUE THREAD

**Issue by markusstephanides** [Noesis/UE4Plugin#21]
Hello! 

I just wanted start using NoesisGUI for my unreal project using version 4.25.1 with the downloadable plugin from the website but when I'm building I get these error messages:

![image](https://user-images.githubusercontent.com/6057570/85768371-3d602d00-b719-11ea-965e-a429edf4d205.png)

Thanks in advance for any help!

**Comment by hcpizzi** [comment]
Hi markusstephanides,

We are in the process of updating the plugin. There are some issues that we want to address, that’s why it’s taking longer than usual. We’ll announce it once it’s out. Please, bear with us while we get it sorted.
