### ISSUE TITLE
Doesn't work in UE4.15

### ISSUE THREAD

**Issue by jashking** [Noesis/UE4Plugin#4]
According to the How to use,

> Open the blueprint and click on Class Settings in the top bar. Edit the Base Xaml property to refer to the NoesisGuiXaml imported in the first step.

There is no BaseXaml property. Should change UPROPERTY() to UPROPERTY(EditAnywhere). Then BaseXaml is editable.

> Create an instance of the NoesisGuiBlueprint object using the CreateWidget function and call AddToViewport/AddToPlayerScreen as you would with a native UE4 widget.

Doesn't show anything on the screen! How to make it works?

**Comment by hcpizzi** [comment]
Hi,

Hopefully you've already figured it out.

Please, refer to the [HelloWorld](https://github.com/Noesis/Tutorials/tree/master/Samples/HelloWorld/UE4) sample for an introduction to Noesis and UE4.

I'm closing this issue. If you still run into problems, please open a new one.
