### ISSUE TITLE
Android & iOS support?

### ISSUE THREAD

**Issue by RPG3D** [Noesis/UE4Plugin#5]
Android & iOS support?

**Comment by hcpizzi** [comment]
Hello,

Support for both is coming soon. We'll announce it once it's done.

**Comment by hcpizzi** [comment]
@RPG3D iOS support has been added in the latest commit.

Let us know if you find any problems with it.

Android will be coming next.

**Comment by hcpizzi** [comment]
Both Android and iOS are now supported. I'm closing this issue.
