### ISSUE TITLE
Blueprint call NotifyArrayChanged cause crash

### ISSUE THREAD

**Issue by RPG3D** [Noesis/UE4Plugin#8]
file: NoesisTypeClass.cpp
line: 2240 

void NoesisNotifyArrayPropertyChanged(UObject* Owner, FName ArrayPropertyName)
{
	Noesis::Ptr<Noesis::BaseComponent>* WrapperPtr = ObjectMap.Find(Owner);
	if (WrapperPtr)
	{
		NoesisObjectWrapper* Wrapper = (NoesisObjectWrapper*)WrapperPtr->GetPtr();
		const Noesis::TypeClass* WrapperTypeClass = Wrapper->GetClassType();
		const Noesis::TypeProperty* ArrayTypeProperty = WrapperTypeClass->FindProperty(NsSymbol(TCHARToNsString(*ArrayPropertyName.ToString())));

//ArrayTypeProperty is nullptr

		NoesisArrayWrapperBase* Array = (NoesisArrayWrapperBase*)(ArrayTypeProperty->GetComponent(Wrapper).GetPtr());
		Array->NotifyChanged();
	}
}

**Comment by hcpizzi** [comment]
I've added extra validation to NoesisNotifyArrayPropertyChanged in the latest commit to the master branch (eda0951d866bf3e899678bfb9da2a4742cc6ec37).

**Comment by RPG3D** [comment]
may be the NoesisNotifyArrayPropertyChanged() will not find the property, if the array is defined in c++ ,
UPROPERTY(EditAnywhere, BlueprintReadWrite)
TArray<[UStructType]> ItemsSource;

**Comment by hcpizzi** [comment]
I added the extra validation in NoesisNotifyArrayPropertyChanged, and verified that it does indeed work with native TArrays. I'm closing this issue.
